### ISSUE TITLE
ENH: Add additional segmenting algorithms (meta issue)

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/vocalpy#55]
This is a meta issue that tracks additional segmenting algorithms as discussed in #40. Not all of these will be added, this issue is just a place to throw basically *all* algorithms we could possibly add.

Notice here I am grouping them by whether they produce a `Sequence` or a set of `Boxes` as discussed in #40, #49, #50, #51

  - [ ] sequences
    - [ ] `endpoint_detection`, AKA Rabiner-Sambur algorithm 
    - [ ] whatever evsonganaly uses -- is there a name? `amplitude_threshold`
    - [ ] Harma
    - [ ] ava (added in #53 to fix #46 )
    - [ ] vocalseg -- "dynamic thresholding"
    - [ ] usvseg: https://github.com/vocalpy/vocalpy/issues/43
    - [ ] Yu Troyer 2006 zebra finch algorithm -- gets cited a lot, I don't find any public implementations
  - [ ] boxes
    - [ ] Lasseck
    - [ ] vocalseg -- the other one
